name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use nightly toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        default: true
        override: true
    - name: Setup Diesel
      run: |
        sudo apt-get update -qq && \
        sudo apt-get install -y libsqlite3-dev && \
        cargo install diesel_cli --no-default-features --features sqlite && \
        diesel setup
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
